### ISSUE TITLE
US08 - Reportar Bug

### ISSUE THREAD

**Issue by MatheusMiranda** [fga-gpp-mds/2017.1-PlataformaJogosUnB#25]
# Descrição
US02 - Como um usuário eu gostaria de reportar bugs dos jogos para informar erros aos desenvolvedores.

# Pontos
Sprint 1: 8

# Critérios de aceitação

- [ ]  O usuário deve poder reportar o jogo a partir da página do jogo;
- [ ] Usuário pode comentar como Anônimo;
- [ ] O bug reportado deve ser mapeado para uma issue no repositório oficial do jogo no GitHub;
- [ ] A quantidade de bugs do jogo reportados através da plataforma é contabilizada;
- [ ] A API fornece as informações dos bugs contabilizados do jogo;

# PR

Deve ser aberto o pull request ao concluir os critérios de aceitação e cumprir com a definição de [pronto](https://github.com/fga-gpp-mds/2017.1-PlataformaJogosUnB/wiki/Planejamento-da-release-2#2---defini%C3%A7%C3%A3o-de-pronto).

**Comment by marcelohpf** [comment]
Moved to other US in epic Statistic
A quantidade de bugs do jogo reportados através da plataforma é contabilizada;
A API fornece as informações dos bugs contabilizados do jogo;
