### ISSUE TITLE
Problema na view de game

### ISSUE THREAD

**Issue by marcelohpf** [fga-gpp-mds/2017.1-PlataformaJogosUnB#45]
# Descrição:

A view de game apresenta o problema de não conseguir mandar atualização do banco de dados assim é feito um registro. Ela apenas entrega os registros com o reinício do servidor!

# Passos para reprodução:

1. Rodar servidor
1. Abrir browser na rota localhost:8000/
1. Verificar jogos que aparecem na tela.
1. Adicionar um novo registro de Game
    1. Adicionar pelo django admin
    1. Adicionar pelo ```python3 manage.py shell_plus```
        1. Usando ```GameFactory()```
        1. Usando ```Game.objects.create()```
    1. Adicionar em comando SQL ```python3 manage.py dbshell```
1. Verificar a tela aberta no localhost:8000/

# Resultado obtido

1. Na tela do browser, os jogos adicionados não são exibidos, mesmo dando o Refesh na página.
1. Só são exibidos os registros cadastrados antes do início do servidor.
1. Todos os registros novos e antigos são retornados em uma lista de QuerySet.

# Resultado esperado

1. Que os 3 novos registros adicionados aparecessem na tela sem necessidade de refresh
1. Usando o comando ```curl -X GET http://localhost:8000/games/list.json``` deve aparecer os 3 registros adicionados.
1. Abrir o ```python3 manage.py shell_plus``` e ver os registros em ```Game.objects.all()```

**Comment by arthurTemporim** [comment]
Add queryset to method list in view.
