### ISSUE TITLE
US21 - Definir obrigatoriedade de imagem de capa

### ISSUE THREAD

**Issue by joaorobson** [fga-gpp-mds/2017.1-PlataformaJogosUnB#7]
US21 - Eu como administrador preciso que uma imagem de capa seja enviada para cada jogo para o layout da plataforma não ser comprometido. 

Pontos: 5

Critérios de aceitação:
- [x] Deve ser validado se exite uma unica imagem de capa referente a um jogo.
- [x] Caso não haja nenhuma imagem deve ser informado ao usuário: "Não há nenhuma imagem de capa. Por favor adicioná la." 
- [x] Caso haja mais de uma imagem selecionada como imagem de capa deve ser informado ao usuário: "Por favor selecionar apenas uma imagem de capa."
- [x] Caso o processo obtenha sucesso deve ser informado ao usuário: "Imagem de capa escolhida com sucesso!".
- [x] Deve se ter teste unitários para os possíveis fluxos 
- [ ] Deve se ter teste de aceitação para os possíveis fluxos

**Comment by arthurTemporim** [comment]
1º A imagem de capa agora é um atributo de Game. Logo ela está relacionada ao jogo e validação sobre sua existência foram implementadas.

**Comment by arthurTemporim** [comment]
3º Como agora a imagem de capa é um atributo, então não tem como selecionar mais de uma.
