### ISSUE TITLE
US21- Compartilhar jogo

### ISSUE THREAD

**Issue by MatheusMiranda** [fga-gpp-mds/2017.1-PlataformaJogosUnB#85]
# Descrição
Eu como jogador desejo compartilhar os jogos no facebook, para que mais pessoas possam conhecê-los.

# Critérios de aceitação
- [ ] Ao clicar em "share" deve ser possível compartilhar o jogo no Facebook.

**Comment by arthurTemporim** [comment]
Tem que configurar o **publish_actions** to **facebook developer** para funcionar.
